using SharpClaw.Contracts.Entities.Core.Context;
using SharpClaw.Contracts.Entities;
using SharpClaw.Contracts.Enums;
using SharpClaw.Contracts.Entities.Core;

namespace SharpClaw.Contracts.Entities.Core.Jobs;

/// <summary>
/// Persisted record of an agent action job.  Tracks the full lifecycle
/// from submission through permission evaluation, optional approval,
/// execution, and final outcome.
/// </summary>
public class AgentJobDB : BaseEntity
{
    public Guid AgentId { get; set; }
    public AgentDB Agent { get; set; } = null!;

    // ── Caller identity (who submitted the job) ───────────────────
    public Guid? CallerUserId { get; set; }
    public Guid? CallerAgentId { get; set; }

    // ── Action definition ─────────────────────────────────────────

    /// <summary>
    /// Canonical dispatch key identifying the module tool to execute
    /// (e.g. "execute_as_safe_shell", "cu_enumerate_windows").
    /// Every job must have an ActionKey — it is the sole routing mechanism.
    /// Historical jobs created before ActionKey was introduced may have a
    /// <c>null</c> value; those jobs are inert and cannot be re-executed.
    /// </summary>
    public string? ActionKey { get; set; }

    public Guid? ResourceId { get; set; }

    /// <summary>
    /// Payload submitted with the job.  The format depends on the
    /// action type or module envelope.
    /// </summary>
    public string? ScriptJson { get; set; }

    /// <summary>
    /// Absolute path where the dangerous shell process should be
    /// spawned.  Overrides the <see cref="SystemUserDB.WorkingDirectory"/>
    /// when set.  Not validated or sandboxed — dangerous by design.
    /// </summary>
    public string? WorkingDirectory { get; set; }

    // ── State ─────────────────────────────────────────────────────
    public AgentJobStatus Status { get; set; } = AgentJobStatus.Queued;
    public PermissionClearance EffectiveClearance { get; set; } = PermissionClearance.Unset;

    // ── Outcome ───────────────────────────────────────────────────
    public string? ResultData { get; set; }
    public string? ErrorLog { get; set; }

    // ── Token usage (accumulated during chat-driven tool calls) ───

    /// <summary>
    /// Prompt tokens consumed by LLM rounds that included this job's
    /// tool call.  Null when the job was not part of a chat tool loop
    /// or when the provider did not report usage.
    /// </summary>
    public int? PromptTokens { get; set; }

    /// <summary>
    /// Completion tokens generated by LLM rounds that included this
    /// job's tool call.  Null when the job was not part of a chat tool
    /// loop or when the provider did not report usage.
    /// </summary>
    public int? CompletionTokens { get; set; }

    // ── Timestamps ────────────────────────────────────────────────
    public DateTimeOffset? StartedAt { get; set; }
    public DateTimeOffset? CompletedAt { get; set; }

    // ── Approval ──────────────────────────────────────────────────
    public Guid? ApprovedByUserId { get; set; }
    public Guid? ApprovedByAgentId { get; set; }

    // ── Channel (required — every job belongs to a channel) ───
    public Guid ChannelId { get; set; }
    public ChannelDB Channel { get; set; } = null!;

    // ── Logs ──────────────────────────────────────────────────────
    public ICollection<AgentJobLogEntryDB> LogEntries { get; set; } = [];
}
